Fixing n+1 query problem
LoviMadaan/Simple_blog pull request #9
Opened 2023-07-19 10:07 UTC by LoviMadaan

2023-07-19 15:14 UTC, elisha2kyakpo1 requested changes
Hi 👋 @LoviMadaan, and @dieum512 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ The PR title and description are good and professional.
✔️ No linter errors.
✔️ Descriptive readme file.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 15:14 UTC, elisha2kyakpo1 commented on spec/helpers/post_helper_spec.rb
>            concat content_tag(:h3, post.title)
- [ ] Kindly fix the naming of files, I couldn't test the app because I was getting an error about helpers, if this is a problem with my laptop, please share a screenshot where tests are passing the next reviewer.

![helps](https://github.com/LoviMadaan/Simple_blog/assets/53124548/99aa922e-42b0-40d7-a623-b62f9ccebe59)

2023-07-20 06:02 UTC, LoviMadaan commented on app/controllers/posts_controller.rb
>    end
Please check the posts_helper file.. I have implemented the include menthod there.. 


![Screenshot 2023-07-20 112859](https://github.com/LoviMadaan/Simple_blog/assets/119787828/8c3b077d-fd29-41d2-a9f5-df54827bfe47)

2023-07-20 06:03 UTC, LoviMadaan commented on spec/helpers/post_helper_spec.rb
>            concat content_tag(:h3, post.title)
### Here I am attaching the screeshot of all tests passing:-

![Screenshot 2023-07-20 112725](https://github.com/LoviMadaan/Simple_blog/assets/119787828/c232a9eb-4422-4a19-ade3-7326ba3476e5)

2023-07-20 06:18 UTC, KayLemba approved these changes
[[[# STATUS: APPROVED :green_circle: :clap: 

Hello @LoviMadaan        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  a. 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] No linter errors
- [x] App Works as intended 💯
- [x] Tests are passing 💯 

 

 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]] 
](https://github.com/fatmahussein/To-do-list.git)

2023-07-20 06:21 UTC, merged